org: ramphealth
app: pdf-s3
service: pdfToS3Lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-west-2'}
  endpointType: REGIONAL
  stage: ${opt:stage, 'dev'}
  timeout: 25
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

  iam:
    role:
      name: ramp-s3uploader
      statements:
        # Allow functions to list all buckets
        - Effect: 'Allow'
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action: 
          - - Effect: Allow
          Action: 
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:PutObjectAcl'
            - 's3:PutObjectTagging'
            - 's3:PutObject'
            - 's3-object-lambda:Get*'
            - 's3-object-lambda:List*'
          Resource:
            - "arn:aws:s3:::ramp-pdf-bucket/*"
package:
  patterns:
    - '!.cache/**'
    - '!markup.html'
    - '!array.php'
    - '!chromium-test.js'

functions:
  api:
    architecture: 'x86_64'
    handler: handler.handler
    memorySize: 2048
    events:
      - httpApi:
          path: /api/pdf-generate
          method: post
